# Generated by Django 4.2.1 on 2023-06-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='qualification',
            field=models.CharField(max_length=128),
        ),
    ]
